export const experienceData = [
  {
    position: 'Full Stack Developer',
    company: 'Moonlite Media',
    date: 'Feb. 2024 - Present',
    description: '',
    tags: ['Next.js', 'Typescript', 'Tailwind'],
    link: 'https://www.moonlitemedia.ca/home',
    imageUrl: '/moonlitemedia.png',
    alt: 'Moonlite Media Logo',
  },
  {
    position: 'Software Developer',
    company: 'ConstructionClock (RoofBundle)',
    date: 'May. 2021 - Jun. 2022',
    description: '',
    tags: ['React', 'NodeJS', 'MongoDB'],
    link: 'https://constructionclock.com/',
    imageUrl: '/constructionclock.png',
    alt: 'Construction Clock Logo',
  },
  {
    position: 'Frontend Developer (Intern)',
    company: 'Arctic Research Foundation',
    date: 'Oct. 2020 - Apr. 2021',
    description: '',
    tags: ['React', 'NodeJS', 'MongoDB'],
    link: 'https://www.arcticfocus.org/',
    imageUrl: '/arf.png',
    alt: 'Construction Clock Logo',
  },
] as const;

export const projectsData = [
  {
    title: 'MCSR Ranked',
    description: '',
    tags: [''],
    imageUrl: 'click',
    link: 'https://github.com/Lowgy/ranked-site',
    isLink: true,
    alt: 'MCSR Ranked Image',
  },
  {
    title: 'Fantasy Football Trade Generator',
    description: '',
    tags: ['Next.js', 'Typescript', 'Tailwind', 'PostgreSQL'],
    imageUrl: '',
    link: 'https://fantasy-trade-generator.vercel.app/',
    isLink: true,
    alt: 'Fantasy Football Trade Generator Project Image',
  },
  {
    title: 'D1 Atlas',
    description: '',
    tags: [''],
    imageUrl: '',
    link: 'https://github.com/Lowgy/d1-atlas',
    isLink: true,
    alt: 'D1 Atlas Image',
  },
  {
    title: 'NoPixel InfoHub',
    description: '',
    tags: [''],
    imageUrl: '',
    link: 'https://github.com/Lowgy/nopixel-infohub',
    isLink: true,
    alt: 'NoPixel InfoHub Project Image',
  },
] as const;
